name: http_server
version: 0.9.8+4-dev
description: Library of HTTP server classes.
homepage: https://www.github.com/dart-lang/http_server

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  mime: ^0.9.0
  path: ^1.0.0

dev_dependencies:
  pedantic: ^1.3.0
  test: ^1.2.0
